import Image from 'next/image'

export const services = [
    {
        name: 'AWS DynamoDB',
        service: 'aws_dynamodb',
        category: 'Database',
        description: 'Amazon DynamoDB is a fully managed, serverless, key-value NoSQL database designed to run high-performance applications at any scale. DynamoDB offers built-in security, continuous backups, automated multi-region replication, in-memory caching, and data export tools.',
        image: '/logos/aws-dynamodb.svg',
        credentials: ['region', 'access key', 'secret key'],
    },
    {
        name: 'SharePoint Online',
        category: 'Content Management',
        service: 'sharepoint_online',
        description: 'Share and manage content, knowledge, and applications to empower teamwork, quickly find information, and seamlessly collaborate across the organization.',
        image: '/logos/sharepoint.jpg',
        credentials: [
            'tenant id',
            'client id',
            'client secret',
            'resource id',
            'site domain',
        ],
    },
    {
        name: 'Excel',
        category: 'Document processing',
        service: 'excel',
        description: 'Microsoft Excel is the industry leading spreadsheet software program, a powerful data visualization and analysis tool.',
        image: '/logos/excel.png',
        credentials: [],
    },
    {
        name: 'CSV',
        category: 'Document processing',
        service: 'csv',
        description: 'A Comma Separated Values (CSV) file is a plain text file that contains a list of data. These files are often used for exchanging data between different applications. For example, databases and contact managers often support CSV files.',
        image: '/logos/csv.png',
        credentials: [],
    },
    {
        name: 'AWS S3',
        category: 'File storage',
        service: 'aws_s3',
        description: 'Amazon S3 is cloud object storage with industry-leading scalability, data availability, security, and performance.',
        image: '/logos/s3.png',
        credentials: ['region', 'access key', 'secret key'],
    },
    {
        name: 'Firestore',
        category: 'Database',
        service: 'firestore',
        description: 'Cloud Firestore is a cloud-hosted, NoSQL database that your Apple, Android, and web apps.',
        image: '/logos/firestore.png',
        credentials: [
            'type',
            'project id',
            'private key id',
            'private key',
            'client email',
            'client id',
            'auth uri',
            'token uri',
            'auth provider x509 cert url',
            'client x509 cert url',
        ],
    },
    {
        name: 'MongoDB',
        category: 'Database',
        service: 'mongodb',
        description: 'MongoDB is a source-available cross-platform document-oriented database program. Classified as a NoSQL database program, MongoDB uses JSON-like documents with optional schemas.',
        image: '/logos/mongodb.png',
        credentials: ['connection string'],
    },
    {
        name: 'AWS DocumentDB',
        category: 'Database',
        service: 'aws_documentdb',
        description: 'Amazon DocumentDB is a scalable, highly durable, and fully managed database service for operating mission-critical MongoDB workloads.',
        image: '/logos/documentdb.png',
        credentials: ['region', 'access key', 'secret key'],
    },
    {
        name: 'Postgres',
        category: 'Database',
        service: 'postgres',
        description: 'Postgres, is a free and open-source relational database management system (RDBMS) emphasizing extensibility and SQL compliance.',
        image: '/logos/postgres.png',
        credentials: ['username', 'password', 'host', 'port', 'database'],
    },
    {
        name: 'WooCommerce',
        category: 'Commerce',
        service: 'woocommerce',
        description: "WooCommerce is the world's most popular open-source eCommerce solution. It is a customizable, open-source eCommerce platform built on WordPress. Get started quickly and make your way.",
        image: '/logos/woocommerce.png',
        credentials: ['url', 'consumer key', 'consumer secret', 'version'],
    },
    {
        name: 'Shopify',
        category: 'Commerce',
        service: 'shopify',
        description: 'Shopify is a platform with all the ecommerce and point of sale features you need to start, run, and grow your business.',
        image: '/logos/shopify.png',
        credentials: [
            'shop name',
            'is private',
            'api key',
            'password',
            'access token',
            'api version',
        ],
    },
    {
        name: 'Paystack',
        category: 'Payments',
        service: 'paystack',
        description: 'Paystack is the payment processor of choice for some of the fastest-growing businesses in Nigeria.',
        image: '/logos/paystack.png',
        credentials: ['client secret'],
    },
    {
        name: 'Payfast',
        category: 'Payments',
        service: 'payfast',
        description: 'PayFast is a leading online payment processing solution for individuals, NPOs and businesses in South Africa. It is dedicated to enabling the easy, secure and instant transfer of money to online merchants.',
        image: '/logos/payfast.png',
        credentials: ['merchent id', 'passphrase', 'version'],
    },
    {
        name: 'Dropbox',
        category: 'File storage',
        service: 'dropbox',
        description: 'Dropbox gives you secure access to all your files. Collaborate with friends, family, and coworkers from any device.',
        image: '/logos/dropbox.png',
        credentials: ['client id', 'client secret', 'redirect uri'],
    },
];
